name: whatsapp_helper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  hive:
  hive_flutter:
  provider:
  json_annotation:
  url_launcher: ^5.5.0
  intl: ^0.16.1
  version: ^1.2.0
  http:
  get_version:
  dio:
  permission_handler: ^5.0.1+1
  open_file: ^3.0.1
  flutter_markdown: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  hive_generator:
  json_serializable: ^3.4.0
  flutter_launcher_icons: ^0.7.5
  


dependency_overrides:
  analyzer: '0.39.14'


flutter:
  uses-material-design: true

  
  assets:
    - assets/
    - assets/flags/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

